[package]
name = "stringsimile-service"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
stringsimile-matcher.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
