[package]
name = "stringsimile-service"
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[package.metadata.deb]
name = "stringsimile"
maintainer = "Ensar Sarajčić <dev@ensarsarajcic.com>"
assets = [
    { source = "target/release/stringsimile", dest = "usr/bin/", mode = "755" },
    { source = "../../README.md", dest = "usr/share/doc/stringsimile/README", mode = "644" },
    { source = "../../LICENSE", dest = "usr/share/licenses/stringsimile/LICENSE", mode = "644" },
    { source = "../../distribution/config.yaml", dest = "etc/stringsimile/stringsimile.yaml", mode = "644" },
    { source = "../../distribution/rules/*", dest = "var/lib/stringsimile", mode = "644" },
    { source = "../../target/man/stringsimile.1", dest = "usr/share/man/man1/stringsimile.1", mode = "644" },
    { source = "../../target/man/stringsimile-config.5", dest = "usr/share/man/man5/stringsimile-config.5", mode = "644" },
    { source = "../../target/man/stringsimile-rule-config.5", dest = "usr/share/man/man5/stringsimile-rule-config.5", mode = "644" },
]

[package.metadata.deb.variants.default]
depends = []
default-features = true

[package.metadata.deb.variants.all-dynamic]
depends = ["librdkafka1"]
default-features = false
features = ["all-dynamic"]

[package.metadata.deb.variants.basic]
depends = []
default-features = false
features = ["basic"]

[package.metadata.deb.systemd-units]
unit-scripts = "../../distribution/systemd/"
enable = false
start = false

[package.metadata.generate-rpm]
name = "stringsimile"
maintainer = "Ensar Sarajčić <dev@ensarsarajcic.com>"
assets = [
    { source = "target/release/stringsimile", dest = "/usr/bin/stringsimile", mode = "755" },
    { source = "../../README.md", dest = "/usr/share/doc/stringsimile/README", mode = "644", doc = true },
    { source = "../../LICENSE", dest = "/usr/share/licenses/stringsimile/LICENSE", mode = "644" },
    { source = "../../distribution/systemd/stringsimile.service", dest = "/lib/systemd/system/stringsimile.service", mode = "644" },
    { source = "../../distribution/config.yaml", dest = "/etc/stringsimile/stringsimile.yaml", mode = "644" },
    { source = "../../distribution/rules/*", dest = "/var/lib/stringsimile", mode = "644" },
    { source = "../../target/man/stringsimile.1", dest = "/usr/share/man/man1/stringsimile.1", mode = "644" },
    { source = "../../target/man/stringsimile-config.5", dest = "/usr/share/man/man5/stringsimile-config.5", mode = "644" },
    { source = "../../target/man/stringsimile-rule-config.5", dest = "/usr/share/man/man5/stringsimile-rule-config.5", mode = "644" },
]

[package.metadata.generate-rpm.variants.default]
requires = {}
default-features = true

[package.metadata.generate-rpm.variants.all-dynamic]
requires = { librdkafka = ">= 2.3.0" }
default-features = false
features = ["all-dynamic"]

[package.metadata.generate-rpm.variants.basic]
requires = {}
default-features = false
features = ["basic"]

[features]
default = ["all-static"]
all-static = ["all", "kafka-static"]
all-dynamic = ["all", "kafka-dynamic"]
all = ["all-inputs", "all-outputs"]

basic = []

kafka-static = ["rdkafka/cmake-build"]
kafka-dynamic = ["rdkafka/dynamic-linking"]

all-inputs = ["inputs-kafka"]
inputs-kafka = ["dep:rdkafka"]

all-outputs = ["outputs-kafka"]
outputs-kafka = ["dep:rdkafka"]

[dependencies]
stringsimile-matcher.workspace = true
stringsimile-config.workspace = true

async-stream.workspace = true
clap = { workspace = true, features = ["derive"] }
exitcode.workspace = true
futures.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
metrics-util.workspace = true
rdkafka = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
snafu.workspace = true
sysinfo.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["io-util", "sync"] }
tracing.workspace = true
tracing-subscriber.workspace = true
walkdir.workspace = true

[[bin]]
name = "stringsimile"
path = "src/main.rs"
