[package]
name = "stringsimile-service"
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[package.metadata.deb]
name = "stringsimile"
maintainer = "Ensar Sarajčić <dev@ensarsarajcic.com>"
assets = [
    { source = "target/release/stringsimile", dest = "usr/bin/", mode = "755" },
    { source = "../../README.md", dest = "usr/share/doc/stringsimile/README", mode = "644" },
    { source = "../../LICENSE", dest = "usr/share/licenses/stringsimile/LICENSE", mode = "644" },
]

[package.metadata.deb.systemd-units]
unit-scripts = "distribution/systemd/"
enable = false
start = false

[package.metadata.generate-rpm]
name = "stringsimile"
maintainer = "Ensar Sarajčić <dev@ensarsarajcic.com>"
assets = [
    { source = "target/release/stringsimile", dest = "/usr/bin/stringsimile", mode = "755" },
    { source = "../../README.md", dest = "/usr/share/doc/stringsimile/README", mode = "644", doc = true },
    { source = "../../LICENSE", dest = "/usr/share/licenses/stringsimile/LICENSE", mode = "644" },
    { source = "distribution/systemd/stringsimile.service", dest = "/lib/systemd/system/stringsimile.service", mode = "644" }
]

[dependencies]
stringsimile-matcher.workspace = true
stringsimile-config.workspace = true

async-stream.workspace = true
clap = { workspace = true, features = ["derive"] }
exitcode.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "stringsimile"
path = "src/main.rs"
