[package]
name = "stringsimile-service"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
stringsimile-matcher.workspace = true
stringsimile-config.workspace = true

async-stream.workspace = true
clap = { workspace = true, features = ["derive"] }
exitcode.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
