## This example files displays default values
## Different inputs can be configured here (file input, stdin, kafka)
# input:
  ## To enable file input, define path to read from
  # file_path: null

  ## To enable stdin input, just set the stdin flag to true
  # stdin: false

  ## If stringsimile is built with kafka support, it can be configured using kafka field
  # kafka:
  #   host: localhost
  #   port: 9092
  #   topics: ["stringsimile"]
  #   identifier: stringsimile
  #   pointer: null
  #   librdkafka_options: {}

## Different outputs can be configured here (file output, stdout, kafka)
# output:
  ## To enable file output, define path to write to
  # file_path: null

  ## To enable stdout output, just set the stdout flag to true
  # stdout: false

  ## If stringsimile is built with kafka support, it can be configured using kafka field
  # kafka:
  #   host: localhost
  #   port: 9092
  #   topic: stringsimile
  #   identifier: stringsimile
  #   librdkafka_options: {}

## Rule matcher can be configured here
# matcher:
  ## Path for reading rules can be defined using `rule_path`
  ## It can either be a single file or a directory containing JSONL files
  # rule_path: "/var/lib/stringsimile"

  ## Field to apply rules to from input objects. This field supports simple syntax for accessing nested objects
  ## e.g. ".domain_name" will look for "domain_name" key in root object.
  ## ".value.domain_name" will look for "value" in root object
  ## and then for "domain_name" in the "value" object.
  ## Any failures in matching will just pass through the object unmodified.
  # input_field: ".domain_name"

  ## `report_all` flag can be set to true to put matching metadata in all objects,
  ## even in cases when there was no successful match. This can be useful for debugging
  ## the rules.
  # report_all: false

## stringsimile metrics exporters can be configured here
## All metrics are exported in prometheus format
# metrics:
  ## Export metrics to file
  # file:
    # file_path: "/var/lib/node-exporter/stringsimile.prom"
    # export_interval_secs: 15
    # mode: 0o644

  ## Export metrics to stdout
  # stdout:
    # export_interval_secs: 15

  ## Prefix to add to all metrics names
  # name_prefix: stringsimile

## stringsimile process configuration
# process:
  ## Log level can be configured
  ## Valid levels are: "error", "warn", "info", "debug", "trace"
  # log_level: "INFO"

  ## Number of threads to use
  ## Defaults to number of available cores
  # threads: null

  ## Graceful shutdown timeout in milliseconds
  ## When SIGINT is received, stringsimile will allow time for processing to complete gracefully, before resorting to forceful shutdown
  # shutdown_timeout_ms: 60000
