[package]
name = "stringsimile-matcher"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["all"]
all = ["rules-levenshtein", "rules-jaro", "rules-jaro-winkler", "rules-confusables", "rules-damerau-levenshtein"]
rules-levenshtein = ["dep:triple_accel"]
rules-jaro = ["dep:strsim"]
rules-jaro-winkler = ["dep:strsim"]
rules-confusables = ["dep:confusables"]
rules-damerau-levenshtein = ["dep:triple_accel"]

[dependencies]
confusables = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
strsim = { workspace = true, optional = true }
tracing.workspace = true
triple_accel = { workspace = true, optional = true }
