[package]
name = "stringsimile-matcher"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[features]
default = ["all"]
all = ["rules-levenshtein"]
rules-levenshtein = ["dep:triple_accel"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
triple_accel = { workspace = true, optional = true }
